#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v25
# autospec commit: 9594167
#
Name     : rlwrap
Version  : 0.46.2
Release  : 9
URL      : https://github.com/hanslub42/rlwrap/archive/v0.46.2/rlwrap-0.46.2.tar.gz
Source0  : https://github.com/hanslub42/rlwrap/archive/v0.46.2/rlwrap-0.46.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: rlwrap-bin = %{version}-%{release}
Requires: rlwrap-data = %{version}-%{release}
Requires: rlwrap-license = %{version}-%{release}
Requires: rlwrap-man = %{version}-%{release}
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The filters in this directory have been written to test rlwrap,
not to be practical.

%package bin
Summary: bin components for the rlwrap package.
Group: Binaries
Requires: rlwrap-data = %{version}-%{release}
Requires: rlwrap-license = %{version}-%{release}

%description bin
bin components for the rlwrap package.


%package data
Summary: data components for the rlwrap package.
Group: Data

%description data
data components for the rlwrap package.


%package dev
Summary: dev components for the rlwrap package.
Group: Development
Requires: rlwrap-bin = %{version}-%{release}
Requires: rlwrap-data = %{version}-%{release}
Provides: rlwrap-devel = %{version}-%{release}
Requires: rlwrap = %{version}-%{release}

%description dev
dev components for the rlwrap package.


%package license
Summary: license components for the rlwrap package.
Group: Default

%description license
license components for the rlwrap package.


%package man
Summary: man components for the rlwrap package.
Group: Default

%description man
man components for the rlwrap package.


%prep
%setup -q -n rlwrap-0.46.2
cd %{_builddir}/rlwrap-0.46.2
pushd ..
cp -a rlwrap-0.46.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746454726
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%reconfigure --disable-static
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1746454726
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rlwrap
cp %{_builddir}/rlwrap-%{version}/COPYING %{buildroot}/usr/share/package-licenses/rlwrap/dfac199a7539a404407098a2541b9482279f690d || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/rlwrap
/usr/bin/rlwrap

%files data
%defattr(-,root,root,-)
/usr/share/rlwrap/completions/coqtop
/usr/share/rlwrap/completions/testclient
/usr/share/rlwrap/filters/README
/usr/share/rlwrap/filters/RlwrapFilter.3pm
/usr/share/rlwrap/filters/RlwrapFilter.pm
/usr/share/rlwrap/filters/censor_passwords
/usr/share/rlwrap/filters/censor_passwords.py
/usr/share/rlwrap/filters/count_in_prompt
/usr/share/rlwrap/filters/count_in_prompt.py
/usr/share/rlwrap/filters/debug_null
/usr/share/rlwrap/filters/dissect_prompt
/usr/share/rlwrap/filters/edit_history
/usr/share/rlwrap/filters/ftp_filter
/usr/share/rlwrap/filters/ftp_filter.py
/usr/share/rlwrap/filters/handle_hotkeys
/usr/share/rlwrap/filters/handle_hotkeys.py
/usr/share/rlwrap/filters/handle_sigwinch
/usr/share/rlwrap/filters/history_format
/usr/share/rlwrap/filters/listing
/usr/share/rlwrap/filters/logger
/usr/share/rlwrap/filters/logger.py
/usr/share/rlwrap/filters/makefilter
/usr/share/rlwrap/filters/null
/usr/share/rlwrap/filters/null.py
/usr/share/rlwrap/filters/outfilter
/usr/share/rlwrap/filters/paint_prompt
/usr/share/rlwrap/filters/paint_prompt.py
/usr/share/rlwrap/filters/pipeline
/usr/share/rlwrap/filters/pipeto
/usr/share/rlwrap/filters/pipeto.py
/usr/share/rlwrap/filters/rlwrapfilter.py
/usr/share/rlwrap/filters/scrub_prompt
/usr/share/rlwrap/filters/simple_macro
/usr/share/rlwrap/filters/template
/usr/share/rlwrap/filters/unbackspace

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/RlwrapFilter.3pm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rlwrap/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rlwrap.1
